[[mgr.prepend_keymap]]
on = ["c", "y"]
run = [ 
  'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "escape --select"
]
desc = "Copy to Clipboard"

[[mgr.prepend_keymap]]
on = ["c", "z"]
run  = ['shell --interactive --cursor=2 -- z=.zip; set --; for p in %s; do set -- "$@" "${p##*/}"; done; zip -r "$z" "$@"', "escape --select"]
desc = "Zip selected files (or hovered) with name prompt"

